baseurl         = "https://ianbibby.dev/"
title 		= "~ianbibby/"
theme           = "hugo-notepadium"
copyright   	= "© 2020"

languageCode 	= "us-en"
enableRobotsTXT	= true

[markup.highlight]
codeFences 	= true
noClasses 	= false

[params]
style 		= "dark"
dateFormat 	= "Monday, January 2, 2006"
slogan		= "Musings. Coding. Life."
fullRss 	= false
logo		= "uploads/cover.jpg"

[params.comments]
enable 		= false

[params.syntax]
use 		= "none"
theme 		= "xcode"
darkTheme 	= "xcode-dark"

[params.nav]
showCategories	= true
showTags 	= true

[[params.nav.custom]]
title 		= "About"
url 		= "/about"

[[params.nav.custom]]
title 		= "Categories"
url 		= "/categories"

[[params.nav.custom]]
title 		= "Tags"
url 		= "/tags"

[params.assets]
css		= ["css/font.css", "css/color.css"]
